import "server-only";
import DOMPurify from "isomorphic-dompurify";
import { esc } from "@/lib/pdf/helpers";

/** Same allowlist as the client-side sanitizer, kept independent since this runs in the PDF worker, not the RSC boundary. */
function sanitize(html: string): string {
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: [
      "a", "b", "i", "em", "strong", "p", "ul", "ol", "li", "br", "h1", "h2", "h3", "h4", "h5", "h6",
      "table", "thead", "tbody", "tr", "td", "th", "span", "div", "code", "pre",
    ],
    ALLOWED_ATTR: ["href", "target", "rel"],
  });
}

/** Wraps the Claude-generated PageSpeed AI report HTML in a branded, print-ready page for Puppeteer. */
export function buildInsightReportHtml({ domain, html }: { domain: string; html: string }): string {
  const generatedAt = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>PageSpeed AI Report — ${esc(domain)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; margin: 0; color: #1f2933; font-size: 13px; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .content { padding: 32px 40px 48px; line-height: 1.7; }
  .content h1, .content h2, .content h3, .content h4 { color: #00668c; font-weight: 700; line-height: 1.3; margin: 1.4em 0 0.6em; }
  .content h2 { font-size: 18px; border-bottom: 2px solid #d4eaf7; padding-bottom: 6px; }
  .content h3 { font-size: 15px; }
  .content > h2:first-child, .content > h3:first-child { margin-top: 0; }
  .content p { margin: 0 0 1em; }
  .content ul, .content ol { margin: 0 0 1em; padding-left: 1.4em; }
  .content li { margin: 0.3em 0; }
  .content code { background: #d4eaf7; border-radius: 4px; padding: 0.15em 0.4em; font-size: 0.9em; }
  .content table { width: 100%; border-collapse: collapse; margin: 0 0 1.5em; font-size: 12px; }
  .content th, .content td { border: 1px solid #d9e2e6; padding: 8px 10px; text-align: left; vertical-align: top; }
  .content th { background: #d4eaf7; color: #00668c; font-weight: 700; }
  .content tr:nth-child(even) td { background: #f7fafb; }
</style>
</head>
<body>
<div style="background:#1a1a2e;padding:30px 40px 26px;">
  <h1 style="font-size:22px;color:#fff;font-weight:800;margin-bottom:5px;">PageSpeed AI Report</h1>
  <div style="font-size:13px;color:rgba(255,255,255,0.55);">${esc(domain)}</div>
  <div style="font-size:11px;color:rgba(255,255,255,0.35);margin-top:3px;">Generated by SEOGenieAI &middot; ${generatedAt}</div>
</div>
<div class="content">${sanitize(html)}</div>
</body>
</html>`;
}
