import "server-only";
import {
  FREE_CHECKS,
  PAID_CHECKS,
  auditCard,
  esc,
  fmt,
  fmtDate,
  infoBox,
  kvRow,
  pageHeader,
  safe,
  scoreBg,
  scoreColor,
  scoreLabel,
  secHeader,
} from "@/lib/pdf/helpers";
import { aiBlock } from "@/lib/pdf/ai-block";
import { fixCard } from "@/lib/pdf/fix-card";
import type { FixPlanItem } from "@/lib/audit/types";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Loose = any;

export type PdfReportInput = {
  auditResult: { url: string; domain: string; score: number; audit: Loose };
  paidData: {
    domainAuthority?: Loose;
    backlinks?: Loose;
    domainAge?: Loose;
    aiVisibility?: Loose;
    fixPlan?: FixPlanItem[];
  };
};

/** Composes the 3–4 page report HTML (ported from pdf.controller.js buildHtml). */
export function buildReportHtml({ auditResult, paidData }: PdfReportInput): string {
  const { url, domain, score, audit } = auditResult;
  const da = paidData?.domainAuthority || {};
  const backlinks = paidData?.backlinks || {};
  const domainAge = paidData?.domainAge || {};
  const aiVis = paidData?.aiVisibility || {};
  const fixPlan = Array.isArray(paidData?.fixPlan) ? paidData.fixPlan : [];

  const sc = scoreColor(score);
  const generatedAt = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const allChecks = [...FREE_CHECKS, ...PAID_CHECKS];
  const count = (status: string) =>
    allChecks.filter(({ key }) => audit[key]?.status === status).length;

  const daScore = Number(da.domainAuthority) || 0;
  const paScore = Number(da.pageAuthority) || 0;
  const daColor = daScore >= 50 ? "#16a34a" : daScore >= 30 ? "#ca8a04" : "#dc2626";
  const paColor = paScore >= 50 ? "#16a34a" : paScore >= 30 ? "#ca8a04" : "#dc2626";
  const spamNum = Number(da.spamScore);
  const spamOk = !isNaN(spamNum) && spamNum >= 0;
  const spamLbl = spamOk ? (spamNum <= 30 ? "Low" : spamNum <= 60 ? "Medium" : "High") : "—";
  const spamClr = spamOk ? (spamNum <= 30 ? "#16a34a" : spamNum <= 60 ? "#ca8a04" : "#dc2626") : "#9ca3af";
  const spamBg = spamOk ? (spamNum <= 30 ? "#f0fdf4" : spamNum <= 60 ? "#fefce8" : "#fff1f2") : "#f9fafb";
  const ageNum = Number(domainAge.age);
  const ageOk = !isNaN(ageNum) && ageNum > 0;
  const totalBL = Number(String(backlinks.totalBacklinks || "0").replace(/,/g, ""));
  const dofBL = Number(String(backlinks.dofollowLinks || "0").replace(/,/g, ""));
  const dfPct = totalBL > 0 ? Math.round((dofBL / totalBL) * 100) : null;
  const dfColor = dfPct != null ? (dfPct >= 60 ? "#16a34a" : dfPct >= 40 ? "#ca8a04" : "#dc2626") : "#9ca3af";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AI Readiness Report — ${esc(domain)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, Helvetica, sans-serif; background: #f8fafc; color: #374151; font-size: 13px; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .page-break { page-break-after: always; break-after: page; height: 0; display: block; }
  @media print { .page-break { page-break-after: always; } body { -webkit-print-color-adjust: exact; } }
</style>
</head>
<body>

<div style="background:#1a1a2e;padding:30px 40px 26px;">
  <h1 style="font-size:24px;color:#fff;font-weight:800;margin-bottom:5px;">AI Readiness Report</h1>
  <div style="font-size:13px;color:rgba(255,255,255,0.55);">${esc(url)}</div>
  <div style="font-size:11px;color:rgba(255,255,255,0.35);margin-top:3px;">Generated by SEOGenieAI &middot; ${generatedAt}</div>
</div>

<div style="background:#fff;padding:24px 40px;display:flex;align-items:center;gap:24px;border-bottom:1px solid #e5e7eb;">
  <div style="width:100px;height:100px;border-radius:14px;background:${scoreBg(score)};display:flex;flex-direction:column;align-items:center;justify-content:center;flex-shrink:0;">
    <span style="font-size:48px;font-weight:900;color:${sc};line-height:1;">${score}</span>
    <span style="font-size:11px;font-weight:700;color:${sc};margin-top:2px;">${scoreLabel(score)}</span>
  </div>
  <div style="flex:1;">
    <div style="font-size:20px;font-weight:800;color:#111827;margin-bottom:5px;">${esc(domain)}</div>
    <div style="font-size:13px;color:#9ca3af;margin-bottom:12px;">AI Readiness Score: ${score}/100</div>
    <div style="height:10px;background:#e5e7eb;border-radius:5px;overflow:hidden;">
      <div style="height:10px;border-radius:5px;background:${sc};width:${Math.min(Math.max(score, 0), 100)}%;"></div>
    </div>
    <div style="display:flex;gap:20px;margin-top:10px;font-size:13px;font-weight:700;">
      <span style="color:#16a34a;">&#10003; ${count("pass")} Passed</span>
      <span style="color:#ca8a04;">&#9651; ${count("warn")} Warnings</span>
      <span style="color:#dc2626;">&#10007; ${count("fail")} Failed</span>
    </div>
  </div>
</div>

${secHeader("#16a34a", "Free Report Checks", `(${FREE_CHECKS.length} checks)`)}
<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:0 40px 16px;">
  ${FREE_CHECKS.map(({ key, title }) => auditCard(title, audit[key])).join("")}
</div>

${secHeader("#1a1a2e", "Full Report Checks", `(${PAID_CHECKS.length} checks)`)}
<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:0 40px 28px;">
  ${PAID_CHECKS.map(({ key, title }) => auditCard(title, audit[key])).join("")}
</div>

<div class="page-break"></div>

${pageHeader("Domain Authority, Backlinks & Age", esc(domain))}

${secHeader("#3b82f6", "Domain Authority", "")}
<div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:0 40px 16px;">
  ${infoBox(
    "Authority Scores",
    `
    <div style="display:flex;justify-content:space-around;margin-bottom:14px;">
      <div style="text-align:center;">
        <div style="font-size:40px;font-weight:900;color:${daColor};line-height:1;">${safe(da.domainAuthority)}</div>
        <div style="font-size:11px;color:#9ca3af;margin-top:4px;font-weight:600;">Domain Authority</div>
        <div style="font-size:10px;color:#9ca3af;">out of 100</div>
      </div>
      <div style="width:1px;background:#f3f4f6;"></div>
      <div style="text-align:center;">
        <div style="font-size:40px;font-weight:900;color:${paColor};line-height:1;">${safe(da.pageAuthority)}</div>
        <div style="font-size:11px;color:#9ca3af;margin-top:4px;font-weight:600;">Page Authority</div>
        <div style="font-size:10px;color:#9ca3af;">out of 100</div>
      </div>
    </div>
    <div style="display:flex;justify-content:space-between;align-items:center;padding:6px 0;border-bottom:1px solid #f3f4f6;">
      <span style="font-size:12px;color:#9ca3af;">Spam Score</span>
      <span style="font-size:11px;font-weight:700;padding:3px 10px;border-radius:8px;background:${spamBg};color:${spamClr};">${safe(da.spamScore)}% &mdash; ${spamLbl}</span>
    </div>
    ${kvRow("Linking Domains", fmt(da.linkingDomains))}
    ${kvRow("Inbound Links", fmt(da.inboundLinks))}
    <div style="margin-top:10px;padding:10px;background:#f8fafc;border-radius:8px;font-size:11px;color:#6b7280;line-height:1.5;">
      Domain Authority (DA) is a score that predicts how likely a domain is to rank on search engines. Scores above 50 indicate strong authority.
    </div>
  `
  )}
  ${infoBox(
    "Domain Age",
    `
    <div style="background:#f8fafc;border-radius:8px;padding:16px;text-align:center;margin-bottom:14px;">
      <div style="font-size:40px;font-weight:900;color:#1a1a2e;line-height:1;">${safe(domainAge.age)}</div>
      <div style="font-size:11px;color:#9ca3af;margin-top:4px;font-weight:600;">years old</div>
    </div>
    ${kvRow("Registered", fmtDate(domainAge.registrationDate))}
    ${kvRow("Last Update", fmtDate(domainAge.lastUpdate))}
    ${kvRow("Expires", fmtDate(domainAge.expiryDate))}
    ${domainAge.registrar ? kvRow("Registrar", domainAge.registrar) : ""}
    <div style="margin-top:10px;border-radius:8px;padding:10px 12px;background:${ageOk && ageNum >= 3 ? "#f0fdf4" : "#fefce8"};color:${ageOk && ageNum >= 3 ? "#16a34a" : "#ca8a04"};font-size:11px;line-height:1.6;">
      ${ageOk && ageNum >= 3 ? "&#10003; Established domain — AI systems tend to trust older, stable domains more." : "&#9888; Newer domain — trust takes time. Focus on quality content and consistent backlinks."}
    </div>
  `
  )}
</div>

${secHeader("#7c3aed", "Backlink Profile", "")}
<div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:0 40px 28px;">
  ${infoBox(
    "Link Overview",
    `
    ${kvRow("Total Backlinks", fmt(backlinks.totalBacklinks))}
    ${kvRow("Referring Domains", fmt(backlinks.referringDomains))}
    ${kvRow("Referring Pages", fmt(backlinks.referringPages))}
    ${kvRow("Referring IPs", fmt(backlinks.referringIPs))}
    ${kvRow("Crawled Pages", fmt(backlinks.crawledPages))}
    ${kvRow("Broken Backlinks", fmt(backlinks.brokenBacklinks))}
  `
  )}
  <div>
    ${infoBox(
      "Link Quality",
      `
      ${kvRow("Dofollow Links", fmt(backlinks.dofollowLinks))}
      ${kvRow("Nofollow Links", fmt(backlinks.nofollowLinks))}
      ${kvRow("Government (.gov)", fmt(backlinks.governmentLinks))}
      ${kvRow("Education (.edu)", fmt(backlinks.eduLinks))}
      ${backlinks.spamScore != null ? kvRow("Backlink Spam Score", backlinks.spamScore + "%") : ""}
    `
    )}
    ${
      dfPct != null
        ? infoBox(
            "Dofollow Ratio",
            `
      <div style="text-align:center;padding:8px 0;">
        <div style="font-size:36px;font-weight:900;color:${dfColor};line-height:1;">${dfPct}%</div>
        <div style="font-size:11px;color:#9ca3af;margin-top:4px;">of all links pass link equity</div>
      </div>
      <div style="height:10px;background:#e5e7eb;border-radius:5px;overflow:hidden;margin-top:10px;">
        <div style="height:10px;border-radius:5px;background:${dfColor};width:${Math.min(dfPct, 100)}%;"></div>
      </div>
      <div style="font-size:11px;color:#9ca3af;margin-top:8px;line-height:1.5;">
        Dofollow links pass SEO value to your site. A ratio above 60% is considered healthy.
      </div>
    `
          )
        : ""
    }
  </div>
</div>

<div class="page-break"></div>

${pageHeader("AI Visibility Analysis", `How ChatGPT and Gemini perceive ${domain}`)}

<div style="padding:14px 40px 8px;background:#fff;border-bottom:1px solid #f3f4f6;">
  <p style="font-size:13px;color:#374151;line-height:1.7;">
    AI visibility measures whether and how AI assistants know your brand. When users ask AI tools about products or services in your category, do they mention you?
    High brand awareness and positive sentiment in AI models translates directly into more referral traffic and brand citations.
  </p>
</div>

${secHeader("#7c3aed", "AI Model Perception", "(ChatGPT &amp; Gemini)")}
<div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:0 40px 16px;">
  ${aiBlock(aiVis.chatgpt, "ChatGPT")}
  ${aiBlock(aiVis.gemini, "Gemini")}
</div>

<div style="border-radius:10px;padding:14px 18px;margin:0 40px 20px;background:#eff6ff;border:1px solid #bfdbfe;font-size:13px;color:#1d4ed8;line-height:1.7;">
  <strong>What this means for your business:</strong> AI assistants are increasingly used as search tools.
  When users ask "who sells X" or "best Y supplier", AI models recommend brands they know well.
  Improving your AI visibility means more brand citations and qualified traffic from AI-powered search.
</div>

${
  fixPlan.length > 0
    ? `
<div class="page-break"></div>

${pageHeader("AI-Generated Action Plan", "Prioritised by impact & effort · Powered by Claude")}

<div style="padding:14px 40px 8px;background:#fff;border-bottom:1px solid #f3f4f6;">
  <p style="font-size:13px;color:#374151;line-height:1.7;">
    Based on the ${FREE_CHECKS.length + PAID_CHECKS.length} checks above, Claude has identified the highest-priority actions to improve your AI readiness score.
    These are ranked by the combination of impact on your score and ease of implementation.
  </p>
</div>

${secHeader("#ef4444", "Your Prioritised Action Plan", `(${fixPlan.length} actions)`)}

<div style="padding:8px 40px 24px;">
  ${fixPlan.map((item, i) => fixCard(item, i)).join("")}

  <div style="background:#1a1a2e;border-radius:12px;padding:20px 24px;margin-top:20px;display:flex;align-items:center;justify-content:space-between;">
    <div>
      <div style="color:#fff;font-size:16px;font-weight:800;margin-bottom:5px;">Need help implementing these fixes?</div>
      <div style="color:rgba(255,255,255,0.6);font-size:13px;">Our expert team handles everything — from DNS records to structured data to AI visibility strategy.</div>
    </div>
    <div style="background:#fff;border-radius:8px;padding:10px 22px;font-size:13px;font-weight:700;color:#1a1a2e;white-space:nowrap;margin-left:20px;">Get Expert Help</div>
  </div>
</div>
`
    : ""
}

</body>
</html>`;
}
