import "server-only";
import { esc } from "@/lib/pdf/helpers";

/** Delivery email for the paid PageSpeed AI Report (PDF attached). */
export function buildInsightReportEmailHtml(domain: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 20px;background:#f3f4f6;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08);">
  <tr><td style="background:#1a1a2e;padding:32px 40px;text-align:center;">
    <h1 style="color:#fff;margin:0;font-size:22px;font-weight:700;">PageSpeed AI Report</h1>
    <p style="color:rgba(255,255,255,.55);margin:8px 0 0;font-size:14px;">${esc(domain)}</p>
  </td></tr>
  <tr><td style="padding:28px 40px 32px;font-size:15px;color:#374151;line-height:1.7;">
    <p style="margin:0 0 12px;">Hi,</p>
    <p style="margin:0 0 12px;">
      Your AI-written PageSpeed report for <strong style="color:#111827;">${esc(domain)}</strong> is attached to this email as a PDF — it breaks down every performance, SEO, accessibility and best-practices issue we found, with step-by-step instructions for fixing each one.
    </p>
    <p style="margin:0;">You can also reopen it any time from the report page on SEOGenieAI.</p>
  </td></tr>
  <tr><td style="background:#f9fafb;padding:18px 40px;text-align:center;border-top:1px solid #e5e7eb;">
    <p style="margin:0;color:#9ca3af;font-size:12px;">
      Generated by <strong style="color:#374151;">SEOGenieAI</strong> &middot; One-time report &middot; No subscription
    </p>
  </td></tr>
</table>
</td></tr></table>
</body></html>`;
}
