import "server-only";
import { esc } from "@/lib/pdf/helpers";

const CHECKLIST: [string, string][] = [
  ["All AI readiness checks", "Full audit across HTTPS, robots.txt, sitemap, schema, DNS and more"],
  ["Domain Authority & Backlinks", "DA/PA scores, spam score, referring domains, dofollow ratio"],
  ["Domain Age", "Registration date, expiry, registrar details"],
  ["AI Visibility", "How ChatGPT and Gemini perceive your brand — awareness, sentiment, topics"],
  ["AI Fix Plan", "Prioritised, actionable steps to improve your AI readiness score"],
];

/** Delivery email for the paid report (ported from the legacy webhook). */
export function buildReportEmailHtml(domain: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 20px;background:#f3f4f6;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08);">
  <tr><td style="background:#1a1a2e;padding:32px 40px;text-align:center;">
    <h1 style="color:#fff;margin:0;font-size:22px;font-weight:700;">AI Readiness Report</h1>
    <p style="color:rgba(255,255,255,.55);margin:8px 0 0;font-size:14px;">${esc(domain)}</p>
  </td></tr>
  <tr><td style="padding:28px 40px 8px;font-size:15px;color:#374151;line-height:1.7;">
    <p style="margin:0 0 12px;">Hi,</p>
    <p style="margin:0 0 12px;">
      Your full AI Readiness Report for <strong style="color:#111827;">${esc(domain)}</strong> is attached to this email as a PDF.
    </p>
    <p style="margin:0;">The report includes:</p>
  </td></tr>
  <tr><td style="padding:8px 40px 24px;">
    <table cellpadding="0" cellspacing="0">
      ${CHECKLIST.map(
        ([title, desc]) => `
      <tr>
        <td style="padding:6px 0;vertical-align:top;padding-right:10px;">
          <span style="display:inline-block;width:20px;height:20px;background:#dcfce7;border-radius:50%;text-align:center;line-height:20px;font-size:12px;color:#15803d;font-weight:700;">✓</span>
        </td>
        <td style="padding:6px 0;">
          <strong style="color:#111827;font-size:14px;">${title}</strong>
          <span style="color:#6b7280;font-size:13px;"> — ${desc}</span>
        </td>
      </tr>`
      ).join("")}
    </table>
  </td></tr>
  <tr><td style="padding:0 40px 32px;text-align:center;">
    <p style="font-size:13px;color:#9ca3af;margin:0 0 6px;">
      Can't see the PDF? Check your spam folder or contact support.
    </p>
  </td></tr>
  <tr><td style="background:#f9fafb;padding:18px 40px;text-align:center;border-top:1px solid #e5e7eb;">
    <p style="margin:0;color:#9ca3af;font-size:12px;">
      Generated by <strong style="color:#374151;">SEOGenieAI</strong> &middot; One-time report &middot; No subscription
    </p>
  </td></tr>
</table>
</td></tr></table>
</body></html>`;
}
